### ISSUE TITLE
formInputs.participants only contains one user

### ISSUE THREAD

**Issue by rogeru** [gsuitedevs/gmail-add-ons-samples#10]
Already filed a bug, but got no answer. (https://issuetracker.google.com/issues/77504617)
Now I even get the same problem on the web, not only on Android.

1. In an email with 4 participants, keep all users selected in the "Schedule a meeting" card.
![image](https://user-images.githubusercontent.com/1393401/38711708-5d9df236-3e95-11e8-99f1-830560f67039.png)
2. Click "Find times"
3. Looking at the logs, the formInputs.participants shows only one participant
![image](https://user-images.githubusercontent.com/1393401/38711769-ae264dac-3e95-11e8-86a2-e9d7b14d6aba.png)
4. Therefore when then sending the meeting invite, the meeting only has myself (the one participant)

I have seen this consistently on Android, but now it also happens consistently on the Chrome on the desktop.

**Comment by sqrrrl** [comment]
Is this still occurring? I haven't been able to reproduce this, may have been a temporary regression on the product side.

**Comment by rogeru** [comment]
@sqrrrl just tried again, and yes this is still happening. Tried on web using google's meeting-assistant example. Multiple people in the email, but only one email (the first one) in the formInput(s)

**Comment by rogeru** [comment]
E.g. adding this console.log in function "findTimes"

```  
findTimes: function(e) {
    console.log('aaaa e.formInputs', e.formInputs);
```

Shows only a since participants, event hough the email has 3 participants.

```
textPayload:  "aaaa e.formInputs {duration=[30.0], start=[8.0], end=[18.0], participants=[nikolaosmartzoukos@gmail.com]}"  
```

**Comment by sqrrrl** [comment]
Reproduced. Looks like a bug/regression with switch widgets. Looking in to it.
