### ISSUE TITLE
[Gmail Addon Question] Communication between cards

### ISSUE THREAD

**Issue by sl378** [gsuitedevs/gmail-add-ons-samples#16]
Hi
I wonder if you can help me here,  I read that you can send parameters with actions when building & pushing a new card using the navigation, but what is the best way to send data back to the **previous** card say when you do popCard()

Thank you
Alex

**Comment by grant** [comment]
I think you can store data in `PropertiesService` and read values from there. You can specify what data you want to store before popping the card.

https://developers.google.com/apps-script/reference/properties/

**Comment by sl378** [comment]
Thank you @grant , will give that a try!
