### ISSUE TITLE
The GIT add on suddenly got disappeared

### ISSUE THREAD

**Issue by bishtrial** [gsuitedevs/gmail-add-ons-samples#18]
Hey,
I did all the necessary step to install the add on on Gmail, but when i change the client secret and client id of the git hub account in my script properties, suddenly my add on got disappeared.
If i go to the setting I can still see that the add on is installed , but its not showing in my side pane.
PS I am new to creating add on, any leads will be appreciated.

**Comment by erickoledadevrel** [comment]
Not sure what the cause would be, perhaps try reverting the change and see if that fixes it?
