### ISSUE TITLE
[GitHub Add-on] SyntaxError: Invalid quantifier ?

### ISSUE THREAD

**Issue by erickoledadevrel** [gsuitedevs/gmail-add-ons-samples#20]
After doing a `git pull` and `clasp push`, I'm getting the error `SyntaxError: Invalid quantifier ?` when trying to open the add-on. Reverting 7d0f4f27b3fbc5b4c2fba7da02c7f729e312de0a seems to resolve the issue. I'm not sure what `(?<!<)` or `(?!>)` are trying to do, but that seems to be where the error is located.

**Comment by aandis** [comment]
+1
