### ISSUE TITLE
wrong folder name in meeting assistant documentation

### ISSUE THREAD

**Issue by mderazon** [gsuitedevs/gmail-add-ons-samples#23]
https://github.com/gsuitedevs/gmail-add-ons-samples/blob/master/meeting-assistant/README.md#downloading-the-sample

Instead of 
```
cd gmail-add-ons-samples/github
```
Needs to be
```
cd gmail-add-ons-samples/meeting-assistant
```

**Comment by asrivas** [comment]
Thank you for catching this!
Fixed in:
https://github.com/gsuitedevs/gmail-add-ons-samples/pull/25
