### ISSUE TITLE
Click on schedule meeting is raising error

### ISSUE THREAD

**Issue by SAKSHIC** [gsuitedevs/gmail-add-ons-samples#5]
Hi, 

I am seeing the following issue not sure why. Please help me in resolving it.
An unexpected error occurred
GoogleJsonResponseException: Project 310354644286 is not found and cannot be used for API calls. If it is recently created, enable Calendar API by visiting https://console.developers.google.com/apis/api/calendar.googleapis.com/overview?project=310354644286 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Stack trace
at Settings (Views):24 (getUserTimezone)
at ActionHandlers (Views):33
at Main (Views):103 (dispatchActionInternal)
at Main (Views):53 (handleShowScheduler)

**Comment by sqrrrl** [comment]
Appears that there's something wrong with the underlying developer project attached to the script. If this continues to occur with new projects, let me know.

**Comment by sqrrrl** [comment]
OK, my bad. The readme is missing a setup step to enable the Calendar API in the underlying project. Will update the readme.

**Comment by sqrrrl** [comment]
Updated the readme with the additional instructions.
